import { expect, it } from 'vitest';
import { newState, reduce, restore } from './model';
it('保守柵は支えがばねを受けてから横棒が外れ、通行後も戻せる', () => {
    let s = newState();
    s.room = 'bridge';
    s.camera = 2;
    expect(reduce(s, { type: 'move', room: 'north' })).toBe(s);
    expect(reduce(s, { type: 'gateRod' })).toBe(s);
    expect(reduce(s, { type: 'gateDoor' })).toBe(s);
    s = reduce(s, { type: 'gateSupport' });
    expect(s.values.gateSupport).toEqual([1]);
    expect(reduce(s, { type: 'gateRod' })).toBe(s);
    s.locations.pin = 'inventory';
    s = reduce(s, { type: 'gateRod' });
    expect(s.values.gateRod).toEqual([1]);
    expect(reduce(s, { type: 'gateSupport' })).toBe(s);
    s = reduce(s, { type: 'gateDoor' });
    expect(s.values.gateOpen).toEqual([1]);
    expect(reduce(s, { type: 'gateRod' })).toBe(s);
    expect(restore(JSON.parse(JSON.stringify(s)))).toEqual(s);
    const north = reduce(s, { type: 'move', room: 'north' });
    expect(north.room).toBe('north');
    expect(reduce(north, { type: 'move', room: 'bridge', camera: 2 }).room).toBe('bridge');
    s = reduce(s, { type: 'gateDoor' });
    s = reduce(s, { type: 'gateRod' });
    s = reduce(s, { type: 'gateSupport' });
    expect(s.values).toMatchObject({ gateOpen: [0], gateRod: [0], gateSupport: [0] });
    expect(reduce(s, { type: 'move', room: 'north' })).toBe(s);
});
it('支え・棒・開度の不整合を読み込まず、汎用値操作でも飛び越えない', () => {
    let s = newState();
    s.room = 'bridge';
    s.camera = 2;
    expect(reduce(s, { type: 'values', id: 'gateOpen', values: [1] })).toBe(s);
    s = reduce(s, { type: 'gateSupport' });
    expect(restore({ ...s, values: { ...s.values, gateOpen: [1] } })).toBeNull();
    expect(restore({ ...s, values: { ...s.values, gateRod: [2] } })).toBeNull();
    expect(reduce({ ...s, camera: 0 }, { type: 'gateRod' }).values.gateRod).toBeUndefined();
});
it('開いた柵から支えを外して灯具へ持ち出し、戻せば柵の操作を再開できる', () => {
    let s = newState();
    s.room = 'bridge';
    s.camera = 2;
    s.locations.pin = 'inventory';
    s = reduce(reduce(reduce(s, { type: 'gateSupport' }), { type: 'gateRod' }), { type: 'gateDoor' });
    s = reduce(s, { type: 'take', item: 'support' });
    expect(s.locations.support).toBe('inventory');
    expect(s.values).toMatchObject({ gateSupport: [0], gateRod: [0], gateOpen: [1] });
    expect(restore(JSON.parse(JSON.stringify(s)))).toEqual(s);
    expect(reduce(s, { type: 'gateInstallSupport' })).toBe(s);
    s = reduce(s, { type: 'gateDoor' });
    expect(s.values.gateOpen).toEqual([0]);
    expect(reduce(s, { type: 'gateSupport' })).toBe(s);
    s = reduce(s, { type: 'gateInstallSupport' });
    expect(s.locations.support).toBe('bridgeGate');
    expect(reduce(s, { type: 'gateSupport' }).values.gateSupport).toEqual([1]);
});
