import { ReturnDispatch } from './ReturnDispatch';
import { FreightFocus } from './Freight';
import { NoticeBoard } from './NoticeBoard';
import { FragmentBoard, FragmentPhoto } from './FragmentBoard';
import { ClockChecks, ReceiptTray } from './ForgottenShelf';
import { LampWindow } from './LampWindow';
import { BellPanel } from './Bell';
import { Posters } from './PosterFragments';
import { ShedDoor, BalanceBox } from './LampShed';
import { CargoChest, CargoDocketsView, CargoDocketSheet } from './CargoChest';
import { BridgeGateDetail } from './BridgeGate';
import { HookRack } from './HookRack';
import { RailTagDetail } from './RailTag';
import { Shutter } from './Shutter';
import { ItemImage } from './ItemImage';
import { arrivalTicket } from './arrivalTicket';
import { ToolTrial, PunchGraphic } from './ToolTrial';
import { Train } from './Train';
import { Bag } from './Bag';
import { Photos } from './Photos';
import { Recorder } from './Recorder';
import { RouteCase } from './RouteCase';
import { MaintenanceMap } from './MaintenanceMap';
import { TicketBench, TicketPaper } from './TicketBench';
import { TicketReader } from './TicketReader';
import { Hatch } from './Hatch';
import { CounterDrawer } from './CounterDrawer';
import { ServiceRecords } from './ServiceRecords';
import { PointControls } from './PointControls';
import { JourneyRecords } from './JourneyRecords';
import { OfficeLock } from './OfficeLock';
import { Receipt } from './Receipt';
import { Photo } from './Photo';
import { owns } from './model';
import { Clock } from './Clock';
import type { Focus } from './World';
import type { Action, Item, State } from './model';
export const itemArt: Partial<Record<Item, string>> = { lamp: '/assets/remake/parts/marker-lamp.png', spareLamp: '/assets/remake/parts/marker-lamp.png', envelope: '/assets/remake/parts/seat-envelope.png', officeKey: '/assets/remake/parts/office-key.png', knob: '/assets/remake/parts/reel-cap.png', punch: '/assets/remake/parts/punch-open.png', counterRecords: '/assets/remake/parts/counter-folder.png' };
export function FocusView({ focus, s, dispatch, say, selected, onSelect, close, inspect }: {
    focus: Focus;
    s: State;
    dispatch: (a: Action) => void;
    say: (m: string) => void;
    selected: Item | null;
    onSelect: (i: Item | null) => void;
    close: () => void;
    inspect: (focus: Focus) => void;
}) {
    switch (focus) {
        case 'fragments': return <FragmentBoard s={s} dispatch={dispatch} say={say} photos={() => inspect('fragmentPhoto')}/>;
        case 'fragmentPhoto': return owns(s, 'fragments') ? <FragmentPhoto dispatch={dispatch} say={say}/> : null;
        case 'receiptTray': return <ReceiptTray s={s} dispatch={dispatch} say={say}/>;
        case 'clockChecks': return <ClockChecks s={s} dispatch={dispatch} say={say}/>;
        case 'freight': return <FreightFocus s={s} dispatch={dispatch} say={say}/>;
        case 'noticeBoard': return <NoticeBoard s={s} dispatch={dispatch} say={say} posters={() => inspect('posters')}/>;
        case 'posters': return <Posters s={s} dispatch={dispatch} say={say}/>;
        case 'shedDoor': return <ShedDoor s={s} dispatch={dispatch} say={say} enter={() => dispatch({ type: 'move', room: 'lamp' })}/>;
        case 'balanceBox': return <BalanceBox s={s} dispatch={dispatch} say={say}/>;
        case 'lampWindow': return <LampWindow s={s} dispatch={dispatch} selected={selected} say={say} inspect={inspect} field/>;
        case 'bell': return <BellPanel s={s} dispatch={dispatch} say={say}/>;
        case 'cargoChest': return <CargoChest s={s} dispatch={dispatch} say={say} inspectDockets={() => inspect('cargoDockets')} inspectDocket={() => inspect('cargoDocket')}/>;
        case 'cargoDockets': return <CargoDocketsView dispatch={dispatch} say={say}/>;
        case 'cargoDocket': return <CargoDocketSheet />;
        case 'points': return <PointControls s={s} dispatch={dispatch} say={say}/>;
        case 'passageWindow': return <div className="rm-route-focus"><Photo src="/assets/remake/passage/window.webp" view={[330, 130, 1000, 700]} label="踊り場の窓から見える旧線の橋脚と、その下を抜ける線路"/></div>;
        case 'crossing': return <div className="rm-route-focus"><Photo src={'/assets/remake/bridge/east-tag' + (owns(s, 'pin') ? '-empty' : '') + '.webp'} view={[425, 150, 800, 620]} label="旧線の橋脚とその下を続く線路"/></div>;
        case 'dispatch': return <ReturnDispatch s={s} dispatch={dispatch} say={say}/>;
        case 'signal': return <Shutter s={s} dispatch={dispatch} say={say} reader={() => inspect('reader')} papers={() => inspect('dispatch')}/>;
        case 'tools': return <ToolTrial s={s} dispatch={dispatch} say={say} openTicket={() => inspect('ticket')}/>;
        case 'seat': return <Train s={s} dispatch={dispatch} closeSeat={s.values.seatFocus?.[0] ?? 2} inspect={() => { }} inspectCase={() => { }} say={say}/>;
        case 'bag': return <Bag s={s} dispatch={dispatch} say={say}/>;
        case 'photos': return <Photos s={s} dispatch={dispatch} say={say}/>;
        case 'recorder': return <Recorder s={s} dispatch={dispatch} say={say} selected={selected} onSelect={onSelect}/>;
        case 'case': return <RouteCase s={s} dispatch={dispatch} say={say}/>;
        case 'map': return <MaintenanceMap />;
        case 'ticket': return <TicketBench s={s} dispatch={dispatch} say={say} records={() => inspect('journeyRecords')}/>;
        case 'journeyRecords': return <JourneyRecords s={s} dispatch={dispatch} say={say}/>;
        case 'reader': return <TicketReader s={s} dispatch={dispatch} say={say}/>;
        case 'hatch': return <Hatch s={s} dispatch={dispatch} say={say}/>;
        case 'counterDrawer': return <CounterDrawer s={s} dispatch={dispatch} say={say}/>;
        case 'notices': return <ServiceRecords s={s} dispatch={dispatch} say={say}/>;
        case 'receipt': return <Receipt />;
        case 'platformClock': return <Photo src="/assets/remake/platform/station.webp" view={[935, 207, 188, 195]} label="ホームの時計"><Clock minutes={23 * 60 + 17} transform="translate(1030 302) scale(.72)"/></Photo>;
        case 'officeLock': return <OfficeLock s={s} dispatch={dispatch} say={say} selected={selected} onSelect={onSelect} enter={() => { dispatch({ type: 'move', room: 'office', camera: 0 }); close(); }}/>;
        case 'paperView': return <div className="rm-hand-paper"><TicketPaper ticket={s.draft}/><button onClick={() => dispatch({ type: 'flipTicket' })}>裏返す</button></div>;
        case 'arrivalTicket': return <div className="rm-hand-paper"><TicketPaper ticket={{ ...arrivalTicket, back: s.values.arrivalTicketBack?.[0] === 1 }}/><button onClick={() => dispatch({ type: 'values', id: 'arrivalTicketBack', values: [s.values.arrivalTicketBack?.[0] === 1 ? 0 : 1] })}>裏返す</button></div>;
        case 'bridgeGate': return <BridgeGateDetail s={s} dispatch={dispatch} say={say} selected={selected}/>;
        case 'hookRack': return <HookRack s={s} dispatch={dispatch} say={say}/>;
        case 'railTag': return <RailTagDetail s={s} dispatch={dispatch} selected={selected} say={say}/>;
        case 'item': return <div className="rm-hand-item">{selected === 'punch' ? <svg viewBox="0 0 1536 1024" aria-label="手元の鋏"><PunchGraphic tool={s.values.punchTool?.[0] ?? 1} transform="translate(0 0)"/></svg> : selected && (itemArt[selected] ? <img src={itemArt[selected]} alt="手元の持ち物"/> : <ItemImage item={selected} state={s}/>)}</div>;
        default: return null;
    }
}
