import { useState } from 'react';
import { PhotoStage } from './PhotoStage';
import type { WorkProps } from './CoreWorkspaces';
import { open } from '../game/model';
function BagGlyph({value}:{value:number}){return <svg key={value} className="wheel-mark" viewBox="-22 -22 44 44" aria-hidden="true"><path d={['M-13 0a13 13 0 1 0 26 0a13 13 0 1 0-26 0','M0-15L14 13H-14Z','M-13-13H13V13H-13Z','M-6-14V14M6-14V14'][value]} fill="none" stroke="#261e11" strokeWidth="2.2"/></svg>}
function RouteSymbol({value,x,y}:{value:number;x:number;y:number}){return <g transform={`translate(${x} ${y})`} fill="none" stroke="#d9cea6" strokeWidth="3">{value===0?<path d="M-11-11L11 11M11-11L-11 11"/>:value===1||value===2?<><path d="M-11 13L0-16L11 13ZM-8 4H8M-5-4H5"/><path d={value===1?'M-17-16V14m-4-24h8m-8 9h8m-8 9h8':'M17-16V14m-4-24h8m-8 9h8m-8 9h8'}/></>:value===3?<circle r="12"/>:<path d="M-12 13V-2a12 12 0 0 1 24 0V13"/>}</g>}
export function RouteCase({s,dispatch,message}:WorkProps){
 const v=s.values.P08??[0,0,0,0,0];const solved=open(s,'P08');
 if(solved)return <PhotoStage src={`./assets/closeups/route-case/${s.taken.includes('P08')?'empty':'open'}.webp`} alt={s.taken.includes('P08')?'鍵を取った路線ケース':'開いた路線ケースに駅務室の鍵'} className="opened-route-case">{!s.taken.includes('P08')&&<button className="office-key-hit" aria-label="ケースの駅務室の鍵を取る" onClick={()=>{dispatch({type:'take',id:'P08'});message('駅務室の鍵を取った。')}}><span>鍵を取る</span></button>}<div className="case-result-note"><small>内側の保守札</small><p>△ 鉄塔　　ニ</p></div></PhotoStage>;
 return <div className="route-case-workspace"><svg className="route-case-canvas" viewBox="545 15 620 870" role="group" aria-label="車内の路線ケース。五つの沿線印。"><image href="./assets/closeups/route-case/closed.webp" width="1672" height="941"/><defs><radialGradient id="dial-metal"><stop stopColor="#5d624a"/><stop offset=".7" stopColor="#333d2f"/><stop offset=".85" stopColor="#ad9362"/><stop offset="1" stopColor="#514b35"/></radialGradient></defs><g fill="#c5b48b" fontSize="22" textAnchor="middle"><text x="832" y="250" letterSpacing="8">沿 線 順</text><text x="832" y="306" fontSize="17">進行　→</text></g>{v.map((n,i)=><g key={i} role="button" tabIndex={0} className="round-dial" aria-label={`${i+1}番の沿線印を回す`} onClick={()=>dispatch({type:'values',id:'P08',value:v.map((m,j)=>i===j?(m+1)%5:m)})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();dispatch({type:'values',id:'P08',value:v.map((m,j)=>i===j?(m+1)%5:m)})}}}><circle cx={679+i*76} cy="580" r="32" fill="url(#dial-metal)" stroke="#c1aa76" strokeWidth="2"/><RouteSymbol value={n} x={679+i*76} y={580}/></g>)}</svg><p className="engraved-note">丸い刻印を押して回す</p></div>;
}
export function BagCase({s,dispatch,message}:WorkProps){
 const [look,setLook]=useState(false);const v=s.values.P02??[0,0,0];const solved=open(s,'P02');
 if(solved)return <PhotoStage src={`./assets/closeups/bag/${s.taken.includes('P02')?'empty':'open'}.webp`} alt={s.taken.includes('P02')?'写真を取り出した鞄':'開いた鞄の中に、五枚の写真'} className="opened-bag">{!s.taken.includes('P02')&&<button className="photos-in-bag" aria-label="鞄の写真を取る" onClick={()=>{dispatch({type:'take',id:'P02'});message('車窓の写真を取った。')}}>写真を取る</button>}</PhotoStage>;
 return <div className="bag-case"><PhotoStage src={look?'./assets/closeups/bag/closed.webp':'./assets/closeups/bag/latch.webp'} alt={look?'鞄の三角の印、二列の補修縫い、丸い留め':'鞄の三つの刻印の輪'}>{!look&&<div className="bag-wheel-row">{v.map((n,i)=><button key={i} aria-label={`${i+1}番の鞄の輪を回す`} onClick={()=>dispatch({type:'values',id:'P02',value:v.map((m,j)=>i===j?(m+1)%4:m)})}><BagGlyph value={n}/></button>)}</div>}</PhotoStage><div className="work-controls"><button onClick={()=>setLook(!look)}>{look?'留め具へ戻る':'鞄の印を見る'}</button></div></div>;
}

