import type { GameState,Action } from '../game/model';
import type { MechanismProps } from './Mechanisms';
import { beam,hookReach,hookObstacles,lampObstacles,plaqueLit } from '../game/geometry';
import { StationPlan } from './Figures';
export function HookReach({v,set}:MechanismProps){
 const r=hookReach(v);
 return <div className="hook-reach"><svg viewBox="0 0 720 420" aria-label="手すりの横から見た断面。垂れた支柱の下を棒が通る。"><rect width="720" height="420" fill="#172624"/><path d="M35 365H650" stroke="#5e685a" strokeWidth="10"/>{hookObstacles.map((o,i)=><rect key={i} {...{x:o.x,y:o.y,width:o.w,height:o.h}} fill="#646e62" stroke="#a1a68d" strokeWidth="3"/>)}<path d="M538 183H568V235H538Z" fill="#c1b78e"/><circle cx="553" cy="195" r="8" fill="#172624"/><path d={`M70 340L${r.end.x} ${r.end.y}L${r.tip.x} ${r.tip.y}`} fill="none" stroke={r.clear?'#b7bab0':'#bd8058'} strokeWidth="8" strokeLinecap="round"/><path d="M35 357L98 328" stroke="#6f5140" strokeWidth="18"/></svg><div className="work-controls">{['棒の角度','伸ばす長さ'].map((name,i)=><label key={name}>{name}<input aria-label={name} type="range" min="0" max="3" value={v[i]} onChange={e=>set(v.map((n,k)=>i===k?Number(e.target.value):n))}/></label>)}<button onClick={()=>set([v[0],v[1],1-v[2]])}>鉤を返す　{v[2]?'上向き':'下向き'}</button></div><p className="world-feedback">{r.caught?'鉤の先が、札の穴を通った。':r.clear?'棒は桟に触れていない。':'棒が桟に当たる。このままでは動かせない。'}</p></div>;
}
export function WallLight({v,set,s,dispatch}:MechanismProps&{s:GameState;dispatch:(a:Action)=>void}){
 const fitted=s.installed.includes('bracket'),b=beam(v),lit=fitted&&plaqueLit(v);
 return <div><svg viewBox="0 0 720 380" aria-label="灯具から保守札までの光の断面"><rect width="720" height="380" fill="#172624"/><path d="M0 320H720" stroke="#4d594f" strokeWidth="8"/><rect x="485" y="121" width="80" height="57" fill={lit?'#c4b888':'#323b31'}/>{lit&&<text x="525" y="158" textAnchor="middle" fill="#30372d" fontSize="23">ヘ → ニ</text>}{fitted&&<path d={`M100 210L${b.end.x} ${b.end.y-12}L${b.end.x} ${b.end.y+12}Z`} fill="#e6d89e" opacity=".35"/>}{lampObstacles.map((o,i)=><rect key={i} x={o.x} y={o.y} width={o.w} height={o.h} fill="#465347" stroke="#727b64" strokeWidth="2"/>)}<rect x="69" y="207" width="45" height="35" fill="#666953"/><circle cx="100" cy="210" r="22" fill={fitted?'#e4ce8e':'#647061'}/><text x="526" y="208" textAnchor="middle" fill="#87917c" fontSize="19">小屋の保守札</text></svg><div className="work-controls">{['高さ','向き'].map((name,i)=><label key={name}>{name}<input aria-label={name} type="range" min="0" max="3" value={v[i]} onChange={e=>set(v.map((n,k)=>i===k?Number(e.target.value):n))}/></label>)}<button disabled={!fitted&&!s.inventory.includes('bracket')} onClick={()=>dispatch({type:fitted?'remove':'install',item:'bracket'})}>{fitted?'金具を外す':'金具を取り付ける'}</button></div><p className="world-feedback">{!fitted?'支えがなく、灯具が下を向いてしまう。':lit?'小屋の保守札に、二つの端子と矢印が浮かぶ。':!b.clear?'光が途中で遮られている。':'光は通るが、札を照らしていない。'}</p></div>;
}
export function ThinPlan({v,set,s,dispatch}:MechanismProps&{s:GameState;dispatch:(a:Action)=>void}){
 const accessible=s.room==='office'||s.opened.includes('P04');const taken=s.taken.includes('P06');
 return <div><StationPlan flip={!v[0]}/><p className="world-feedback">薄い紙。{v[1]?'灯りにかざすと、紙全体へやわらかく光が広がる。':'印刷が裏側まで透けている。'}</p><div className="work-controls"><button onClick={()=>set([1-v[0],v[1]])}>裏返す</button><button onClick={()=>set([v[0],1-v[1]])}>{v[1]?'灯りから下ろす':'灯りにかざす'}</button>{!taken&&<button disabled={!accessible} onClick={()=>dispatch({type:'take',id:'P06'})}>図の間に挟まれた紙を持つ</button>}</div>{!accessible&&!taken&&<p>格子の向こう側に、紙の端が出ている。</p>}</div>;
}
export function TunnelLight({v,set,s}:MechanismProps&{s:GameState}){
 const lit=s.inventory.includes('lamp')&&!!v[1];
 return <div className="tunnel-light"><div className="tunnel-photo"><img src="/assets/scenes/tunnel/main.webp" alt="トンネル脇の灯りと、水たまりに映った灯り"/><svg viewBox="0 0 1672 941" aria-hidden="true">{lit&&<><ellipse cx="541" cy="235" rx="65" ry="48" fill="#e0d19a" opacity=".25"/><text x="550" y="243" fontSize="32" fill="#e0d3a6">ト</text><text x="535" y="646" fontSize="26" fill="#e0d3a6" opacity=".5" transform="translate(0 1264) scale(1 -1)">ト</text></>}</svg></div><div className="work-controls"><button disabled={!s.inventory.includes('lamp')} onClick={()=>set([v[0],1-v[1]])}>{lit?'手元の灯具を閉じる':'手元の灯具を開く'}</button>{['灯りの下の札','水面の札'].map((label,i)=><button key={i} className={v[0]===i?'selected':''} onClick={()=>set([i,v[1]])}>{label}</button>)}</div><p className="world-feedback">{lit?(v[0]===0?'灯りの下の金属札には「ト」。':'水面にも同じ札が、逆さに映る。'):s.installed.includes('lamp')?'持っていた灯具は、ホームの信号箱に取り付けてある。':'暗い金属札が、灯りのすぐ下に付いている。'}</p></div>;
}
